// create/templates/vue/pages/catalog.vue
<template>
  <zmp-page name="catalog">
    <zmp-navbar title="Catalog"></zmp-navbar>
    <zmp-list>
      <zmp-list-item
        v-for="(product) in products"
        :key="product.id"
        :title="product.title"
        :link="`/product/${product.id}/`"
      ></zmp-list-item>
    </zmp-list>
    <zmp-block v-if="products.length === 3">
      <zmp-button fill @click="addProduct">Add Product</zmp-button>
    </zmp-block>
  </zmp-page>
</template>
<script>
  import { useStore } from 'zmp-vue';
  import store from '../store'

  export default {
    setup() {
      const products = useStore('products');

      const addProduct = () => {
        store.dispatch('addProduct', {
          id: '4',
          title: 'Apple iPhone 12',
          description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi tempora similique reiciendis, error nesciunt vero, blanditiis pariatur dolor, minima sed sapiente rerum, dolorem corrupti hic modi praesentium unde saepe perspiciatis.'
        });
      }

      return {
        products,
        addProduct,
      };
    }
  };
</script>

// create/templates/svelte/pages/catalog.svelte
<Page name="catalog">
  <Navbar title="Catalog" />
  <List>
    {#each products as product, index (product.id)}
      <ListItem
        title={product.title}
        link={`/product/${product.id}/`}
      />
    {/each}
  </List>
  {#if products.length === 3}
    <Block>
      <Button fill onClick={addProduct}>Add Product</Button>
    </Block>
  {/if}
</Page>
<script>
  import { Page, Navbar, List, ListItem, Block, Button, useStore } from 'zmp-svelte';
  import store from '../store';

  let products = useStore('products', (value) => (products = value));

  const addProduct = () => {
    store.dispatch('addProduct', {
      id: '4',
      title: 'Apple iPhone 12',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi tempora similique reiciendis, error nesciunt vero, blanditiis pariatur dolor, minima sed sapiente rerum, dolorem corrupti hic modi praesentium unde saepe perspiciatis.'
    });
  }

</script>
