// create/templates/vue/pages/product.vue
<template>
  <zmp-page name="product">
    <zmp-navbar :title="product.title" back-link="Back"></zmp-navbar>
    <zmp-block-title>About {{product.title}}</zmp-block-title>
    <zmp-block strong>
      {{product.description}}
    </zmp-block>
  </zmp-page>
</template>
<script>
  import { useStore } from 'zmp-vue';

  export default {
    props: {
      zmproute: Object,
    },
    setup(props) {
      const products = useStore('products');
      const productId = props.zmproute.params.id;
      let currentProduct;
      products.forEach(function (product) {
        if (product.id === productId) {
          currentProduct = product;
        }
      });
      return {
        product: currentProduct,
      };
    },
  };
</script>

// create/templates/svelte/pages/product.svelte
<Page name="product">
  <Navbar title={currentProduct.title} backLink="Back" />
  <BlockTitle>About {currentProduct.title}</BlockTitle>
  <Block strong>
    {currentProduct.description}
  </Block>
</Page>
<script>
  import { Page, Navbar, BlockTitle, Block, useStore } from 'zmp-svelte';

  export let zmproute;

  const products = useStore('products');
  const productId = zmproute.params.id;
  let currentProduct;
  products.forEach(function (product) {
    if (product.id === productId) {
      currentProduct = product;
    }
  });
</script>
