// create/templates/vue/pages/request-and-load.vue
<template>
  <zmp-page>
    <zmp-navbar :title="`${user.firstName} ${user.lastName}`" back-link="Back"></zmp-navbar>
    <zmp-block strong>
      {{user.about}}
    </zmp-block>
    <zmp-list>
      <zmp-list-item
        v-for="(link, index) in user.links"
        :key="index"
        :link="link.url"
        :title="link.title"
        external
        target="_blank"
      ></zmp-list-item>
    </zmp-list>
  </zmp-page>
</template>
<script>
  export default {
    props: {
      user: Object,
    }
  }
</script>

// create/templates/svelte/pages/request-and-load.svelte
<Page>
  <Navbar title={`${user.firstName} ${user.lastName}`} backLink="Back" />
  <Block strong>
    {user.about}
  </Block>
  <List>
    {#each user.links as link}
      <ListItem
        link={link.url}
        title={link.title}
        external
        target="_blank"
      />
    {/each}
  </List>
</Page>
<script>
  import { Page, Navbar, Block, List, ListItem } from 'zmp-svelte';

  export let user;
</script>
